# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fr.documentation
canonical: https://interop.esante.gouv.fr/ig/documentation # the last part of canonical and id must be the same
name: Documentation
title: Documentation des guides d'implémentation de l'ANS
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: active
version: 0.1.9 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: trial-use
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
    shownav: 'true'

pages:
    index.md:
        title: Accueil
    doc_ps.md:
        title: Professionnels de santé
    mod_nouvel_ig.md:
        title: Quick start IG
        mod_bonnes_pratiques.md:
            title: Bonnes pratiques
        mod_erreurs.md:
            title: Les erreurs courantes
        mod_github.md:
            title: Usage de GitHub
    impl_demarrer_sur_fhir.md:
        title: Quick start FHIR
        impl_bonnes_pratiques.md:
            title: Bonnes pratiques
        impl_instance_hapi.md:
            title: Déployer une instance HAPI
        impl_valider_res.md:
            title: Valider une ressource contre un profil
    autres_ressources.md:
        title: Autres Ressources
        changes.md:
            title: Historique des changements
        tests.md:
            title: Tests
        collaborons.md: 
            title: Collaborons
        about.md: 
            title: A propos

menu:
    Accueil: index.html
    Professionnels de santé : doc_ps.html
    Documentation pour auteurs FHIR:
        Quick start IG: mod_nouvel_ig.html
        Bonnes pratiques: mod_bonnes_pratiques.html
        Les erreurs courantes: mod_erreurs.html
        Usage de GitHub: mod_github.html
    Documentation pour implémenteurs FHIR:
        Quick start FHIR: impl_demarrer_sur_fhir.html
        Bonnes pratiques: impl_bonnes_pratiques.html
        Déployer une instance HAPI: impl_instance_hapi.html
        Valider une ressource contre un profil: impl_valider_res.html
    Autres ressources:
        Tests: tests.html
        Collaborons: collaborons.html
        Historique: changes.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr
        A propos: about.html