# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fr.documentation
canonical: https://interop.esante.gouv.fr/ig/documentation # the last part of canonical and id must be the same
name: Documentation
title: Documentation des guides d'implémentation de l'ANS
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: active
version: 0.1.9 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: trial-use
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
    shownav: 'true'

pages:
    index.md:
        title: Accueil
    doc_ps.md:
        title: Documentation des professionnels de santé
    doc_modeler.md:
        dev_nouvel_ig.md:
            title: Quick start IG
        bonnes_pratiques_modeler.md:
            title: Bonnes pratiques
        erreurs.md:
            title: Les erreurs courantes
        github.md:
            title: Usage de GitHub
    doc_implementer.md:
        demarrer_sur_fhir.md:
            title: Quick start FHIR
        bonnes_pratiques_implementer.md:
            title: Bonnes pratiques
        instance_hapi.md:
            title: Déployer une instance HAPI
        valider_res.md:
            title: Valider une ressource contre un profil
    autres_ressources.md:
        title: Autres Ressources
        changes.md:
            title: Historique des changements
        tests.md:
            title: Tests
        collaborons.md: 
            title: Collaborons

menu:
    Accueil: index.html
    Documentation des professionnels de santé : doc_ps.html
    Documentation des FHIR modelers:
        Quick start IG: dev_nouvel_ig.html
        Bonnes pratiques: bonnes_pratiques_modeler.html
        Les erreurs courantes: erreurs.html
        Usage de GitHub: github.html
    Documentation des FHIR implementers:
        Quick start FHIR: demarrer_sur_fhir.html
        Bonnes pratiques: bonnes_pratiques_implementer.html
        Déployer une instance HAPI: instance_hapi.html
        Valider une ressource contre un profil: valider_res.html
    Autres ressources:
        Tests: tests.html
        Collaborons: collaborons.html
        Historique: changes.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr